defaults:
  - spectrogram_conversion.yaml
  - melscale_conversion.yaml
  - dbscale_conversion.yaml
  - resizer.yaml
  
normalize_waveform: ${module.network.normalize_waveform}
normalize_spectrogram: ${module.network.normalize_spectrogram}
mean: -4.268
std: 4.569