model:
  _target_: uncertainbird.modules.models.audioprotopnet.AudioProtoPNet
  num_classes: 9736

model_name: audioprotopnet
model_type: waveform
torch_compile: False
sample_rate: 32_000
normalize_waveform: null
normalize_spectrogram: null
embedding_size: 
length: 5














