root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}
output_dir: ${hydra:runtime.output_dir}
dataset_path: /Volumes/BigChongusF/Datasets/Huggingface/gadme_v1/data
log_dir: ${paths.output_dir}/logs/

