root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}
output_dir: ${hydra:runtime.output_dir}
dataset_path: /mnt/work/bird2vec/gadme_hf_download/data
log_dir: ${paths.output_dir}/logs/
model_dir: "/mnt/work/bird2vec/models/tflite/BirdNet/v2.4/BirdNET_GLOBAL_6K_V2.4_Model_FP32.tflite" 

