_target_: birdset.datamodule.components.transforms.BaseTransforms
sample_rate: ${module.network.sample_rate}
task: ${datamodule.dataset.task}
max_length: 5 # Attention: this might not work with any model!! -> You must specify it or set to 5s as its done in code
  



