model:
  _target_: src.modules.models.hubert.HubertSequenceClassifier
  checkpoint: facebook/hubert-base-ls960
  num_classes: ${datamodule.dataset.n_classes}

model_name: hubert
model_type: raw
torch_compile: False
sampling_rate: 16_000

# hubert uses the w2v2 featue extractor 






