model:
  _target_: src.modules.models.mobilenet.MobileNetClassifier
  architecture: "mobilenet_v3_large"
  num_classes: ${datamodule.dataset.n_classes}
  num_channels: 1
  checkpoint: null

model_name: mobilenet
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True














