# defaults:
#   - model/embedding_model: birdnet_model.yaml

model:
  _target_: src.modules.models.embedding_models.embedding_classifier_model.EmbeddingClassifier
  num_classes: ${datamodule.dataset.n_classes}
  device: ${trainer.accelerator}
  embedding_model: 
    _target_: src.modules.models.embedding_models.perch_tf_embedding_model.PerchTfEmbeddingModel
    is_embedding: True
    window_size_s: 5.0
    hop_size_s: 5.0
    sample_rate: 32_000
    num_classes: ${datamodule.dataset.n_classes}
    embed_dim: 1280
    model_path: ""
    tfhub_version: 4
    model_key: "taxonomy_model_tf"


model_name: Embedding_Perch
model_type: raw
torch_compile: False
sampling_rate: ${module.network.model.embedding_model.sample_rate}