# defaults:
#   - model/embedding_model: birdnet_model.yaml

model:
  _target_: src.modules.models.embedding_models.embedding_classifier_model.EmbeddingClassifier
  num_classes: ${datamodule.dataset.n_classes}
  device: ${trainer.accelerator}
  embedding_model: 
    _target_: src.modules.models.embedding_models.perch_tf_embedding_model.VGGishTfEmbeddingModel
    is_embedding: True
    window_size_s: 3.0
    hop_size_s: 3.0
    sample_rate: 16_000
    num_classes: ${datamodule.dataset.n_classes}
    embed_dim: 128
    model_path: "https://tfhub.dev/google/vggish/1"
    embedding_index: -1
    logits_index: -1
    model_key: "tfhub_model"


model_name: Embedding_VGGish
model_type: raw
torch_compile: False
sampling_rate: ${module.network.model.embedding_model.sample_rate}