# @package _global_
defaults:
  - _self_
  - datamodule: high_sierras
  - module: embedding_multilabel
  - callbacks: default
  - paths: laptop_local
  - trainer: single_gpu
  - logger: wandb
  - hydra: default
  - extras: default

  - experiment: high_sierras_local_embed_perch_multilabel
  - hparams_search: null
  - debug: null

task_name: "train"
ckpt_path: null
seed: 1

module:
  network: ast
logger:
  wandb:
    mode: online

train: True
test: True
save_state_dict: True

