_target_: src.datamodule.base_datamodule.LoadersConfig
train:
  _target_: src.datamodule.base_datamodule.LoaderConfig
  batch_size: 2
  shuffle: True
  num_workers: 4
  drop_last: False
  persistent_workers: True
  pin_memory: False

valid:
  _target_: src.datamodule.base_datamodule.LoaderConfig
  batch_size: 2
  shuffle: False
  num_workers: 4
  drop_last: False
  persistent_workers: True
  pin_memory: False

test:
  _target_: src.datamodule.base_datamodule.LoaderConfig
  batch_size: 2
  shuffle: False
  num_workers: 4
  drop_last: False
  pin_memory: False