_target_: src.datamodule.components.transforms.BaseTransformer
sampling_rate: ${module.network.sampling_rate}
task: ${datamodule.dataset.task}
max_length: ${module.network.model.tf_model.window_size_s}
  



