_target_: src.modules.models.embedding_models.embedding_classifier_model.EmbeddingClassifier

defaults:
  - tf_model: birdnet_model.yaml

num_classes: ${datamodule.dataset.n_classes}
device: ${trainer.accelerator}
